openapi: 3.0.3
info:
  title: Digital Bank
  description: Digital Bank
  version: 1.2.1
servers:
  - url: 'https://digital_bank.com'
paths:
  /accounts:
    get:
      tags:
        - "Accounts"
      description: Get all accounts
      summary: Get a list of all accounts
      operationId: getAccounts
      responses:
        200:
          $ref: '#/components/responses/AccountList_200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
  /account/{accountId}:
    get:
      tags:
        - "Accounts"
      description: Get an account by id
      summary: Get an account by id
      operationId: getAccountById
      parameters:
        - in: path
          name: accountId
          description: Get an account by id
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/schemas/CrUpdateAccount'
        400:
          $ref: '#/components/schemas/BadRequestBody'
        403:
          $ref: '#/components/schemas/ForbiddenBody'
        500:
          $ref: '#/components/responses/500'
    put:
      tags:
        - "Accounts"
      description: Create or update an existing account
      summary: Create or update an account
      operationId: createOrUpdateAccount
      parameters:
        - in: path
          name: accountId
          description: create oe update an account
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/schemas/CrUpdateAccount'
        400:
          $ref: '#/components/schemas/BadRequestBody'
        403:
          $ref: '#/components/schemas/ForbiddenBody'
        500:
          $ref: '#/components/responses/500'
    delete:
      tags:
        - "Accounts"
      description: Delete an existing account
      operationId: deleteAnAccount
      parameters:
        - in: path
          name: accountId
          description: Delete an account
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/responses/200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
  /transactions:
    get:
      tags:
        - "Transactions"
      description: Get all transactions
      operationId: getTransactions
      summary: Get a list of all transactions
      responses:
        200:
          $ref: '#/components/responses/TransactionList_200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
  /transaction/{transactionId}:
    get:
      tags:
        - "Transactions"
      description: Get a transaction by id
      summary: Get a transaction by id
      operationId: getTransactionById
      parameters:
        - in: path
          name: transactionId
          description: Get a transaction by id
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/schemas/CrUpdateTransaction'
        400:
          $ref: '#/components/schemas/BadRequestBody'
        403:
          $ref: '#/components/schemas/ForbiddenBody'
        500:
          $ref: '#/components/responses/500'
    put:
      tags:
        - "Transactions"
      description: Create or update an existing transaction
      operationId: crUpdateTransactions
      parameters:
        - in: path
          name: transactionId
          description: Create or update an existing transaction
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/schemas/CrUpdateTransaction'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
    delete:
      tags:
        - "Transactions"
      description: Delete a transaction if it has been completed
      operationId: deleteTransaction
      parameters:
        - in: path
          name: transactionId
          description: Delete a transaction if it has been completed
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/responses/200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
  /transaction/{transactionId}/category:
    put:
      tags:
        - "Transactions"
      description: Categorize an existing transaction
      operationId: crUpdateCategory
      parameters:
        - in: path
          name: transactionId
          description: Categorize an existing transaction
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/responses/200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
  /accountsStatements:
    get:
      tags:
        - "Accounts Statements"
      description: Get all accounts statements
      operationId: getAllAccountsStatements
      summary: get a list of all accounts statements
      responses:
        200:
          $ref: '#/components/responses/AccountStatementList_200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
  /accountStatement/{accountStatementId}:
    get:
      tags:
        - "Accounts Statements"
      description: Get an account statement by id
      summary: Get an account statement by id
      operationId: getAccountStatementById
      parameters:
        - in: path
          name: accountStatementId
          description: Get an account statement by id
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/schemas/CreateAccountStatement'
        400:
          $ref: '#/components/schemas/BadRequestBody'
        403:
          $ref: '#/components/schemas/ForbiddenBody'
        500:
          $ref: '#/components/responses/500'
    put:
      tags:
        - "Accounts Statements"
      description: Create or update an existing account statement
      operationId: crUpdateAccountStatement
      parameters:
        - in: path
          name: AccountStatementId
          description: Create or update an existing account statement
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/schemas/CreateAccountStatement'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
    delete:
      tags:
        - "Accounts Statements"
      description: Delete an account statement
      operationId: deleteAccountStatement
      parameters:
        - in: path
          name: AccountStatementId
          description: Delete an account statement
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/responses/200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
  /categories:
    get:
      tags:
        - "Categories"
      description: Get all categories
      summary: A list of categories
      operationId: getCategories
      responses:
        200:
          $ref: '#/components/responses/CategoryList_200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
  /category/{categoryId}:
    get:
      tags:
        - "Categories"
      description: Get a category by id
      summary: Get a category by id
      operationId: getCategoryById
      parameters:
        - in: path
          name: categoryId
          description: Get a category by id
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/schemas/CrUpdateCategory'
        400:
          $ref: '#/components/schemas/BadRequestBody'
        403:
          $ref: '#/components/schemas/ForbiddenBody'
        500:
          $ref: '#/components/responses/500'
    put:
      tags:
        - "Categories"
      description: Create or update an existing a category
      operationId: crUpdateCategory
      parameters:
        - in: path
          name: categoryId
          description: Create or update an existing category
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/schemas/CrUpdateCategory'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
    delete:
      tags:
        - "Categories"
      description: Delete a category
      operationId: deleteCategory
      parameters:
        - in: path
          name: categoryId
          description: Delete a category
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/responses/200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
  /balanceHistories:
    get:
      tags:
        - "Balance Histories"
      description: Get all balance histories
      summary: A list of balance histories
      operationId: getBalanceHistories
      responses:
        200:
          $ref: '#/components/responses/BalanceHistoryList_200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
  /balanceHistory/{balanceHistoryId}:
    get:
      tags:
        - "Balance Histories"
      description: Get a balance history by id
      summary: Get a balance history by id
      operationId: getBalanceHistoryById
      parameters:
        - in: path
          name: balanceHistoryId
          description: Get a balance history by id
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/schemas/CrUpdateBalanceHistory'
        400:
          $ref: '#/components/schemas/BadRequestBody'
        403:
          $ref: '#/components/schemas/ForbiddenBody'
        500:
          $ref: '#/components/responses/500'
    put:
      tags:
        - "Balance Histories"
      description: Create or update an existing balance history
      operationId: crUpdateBalanceHistory
      parameters:
        - in: path
          name: balanceHistoryId
          description: Create or update an existing balance history
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/schemas/CrUpdateBalanceHistory'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
    delete:
      tags:
        - "Balance Histories"
      description: Delete a balance history
      operationId: deleteBalanceHistory
      parameters:
        - in: path
          name: balanceHistoryId
          description: Delete a balance history
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/responses/200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
  /transfer:
    get:
      tags:
        - "Transfer"
      description: Get all transfer
      summary: A list of transfer
      operationId: getTransfer
      responses:
        200:
          $ref: '#/components/responses/TransferList_200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
  /transfer/{transferId}:
    get:
      tags:
        - "Transfer"
      description: Get a transfer by id
      summary: Get transfer by id
      operationId: getTransferById
      parameters:
        - in: path
          name: transferId
          description: Get a transfer by id
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/schemas/CrUpdateTransfer'
        400:
          $ref: '#/components/schemas/BadRequestBody'
        403:
          $ref: '#/components/schemas/ForbiddenBody'
        500:
          $ref: '#/components/responses/500'
    put:
      tags:
        - "Transfer"
      description: Create or update an existing transfer
      operationId: crUpdateTransferHistory
      parameters:
        - in: path
          name: transferId
          description: Create or update an existing transfer
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/schemas/CrUpdateTransfer'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
    delete:
      tags:
        - "Transfer"
      description: Delete a transfer
      operationId: deleteTransfer
      parameters:
        - in: path
          name: transferId
          description: Delete a transfer
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/responses/200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
  /bank:
    get:
      tags:
        - "Bank"
      description: Get all bank
      summary: A list of bank
      operationId: getBank
      responses:
        200:
          $ref: '#/components/responses/BankList_200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
  /bank/{bankId}:
    get:
      tags:
        - "Bank"
      description: Get a bank by id
      summary: Get bank by id
      operationId: getBankById
      parameters:
        - in: path
          name: bankId
          description: Get a bank by id
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/schemas/CrUpdateBank'
        400:
          $ref: '#/components/schemas/BadRequestBody'
        403:
          $ref: '#/components/schemas/ForbiddenBody'
        500:
          $ref: '#/components/responses/500'
    put:
      tags:
        - "Bank"
      description: Create or update an existing bank
      operationId: crUpdateBank
      parameters:
        - in: path
          name: bankId
          description: Create or update an existing bank
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/schemas/CrUpdateBank'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
    delete:
      tags:
        - "Bank"
      description: Delete a bank
      operationId: deleteBank
      parameters:
        - in: path
          name: bankId
          description: Delete a bank
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/responses/200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500:
          $ref: '#/components/responses/500'
components:
  schemas:
    Account:
      type: object
      allOf:
        - $ref: '#/components/schemas/CrUpdateAccount'
    Transaction:
      type: object
      allOf:
        - $ref: '#/components/schemas/CrUpdateTransaction'
    AccountStatement:
      type: object
      allOf:
        - $ref: '#/components/schemas/CreateAccountStatement'
    Category:
      type: object
      allOf:
        - $ref: '#/components/schemas/CrUpdateCategory'
    BalanceHistory:
      type: object
      allOf:
        - $ref: '#/components/schemas/CrUpdateBalanceHistory'
    CrUpdateCategory:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
    CrUpdateTransaction:
      type: object
      properties:
        id:
          type: integer
        transactionDate:
          type: string
          format: date
        amount:
          type: string
          format: bigDecimal
        transactionType:
          type: string
          enum:
            - Debit
            - Credit
        label:
          type: string
    Transfer:
      type: object
      allOf:
        - $ref: '#/components/schemas/CrUpdateTransfer'
    Bank:
      type: object
      allOf:
        - $ref:  '#/components/schemas/CrUpdateBank'
    ResponseStatus:
      type: object
      properties:
        code:
          type: integer
          example: 200
        message:
          type: string
    ResponseBodyTemplate:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/ResponseBodyTemplate'
        body:
          type: object
    BadRequestBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
      example:
        status:
          code: 400
          message: Bad Request
          body: { }
    ForbiddenBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
      example:
        status:
          code: 403
          message: Forbidden
          body: { }
    ErrorServerBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
      example:
        status:
          code: 500
          message: Eternal server error
    AccountListBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
        - properties:
            body:
              type: array
              items:
                $ref: '#/components/schemas/Account'
    TransactionListBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
        - properties:
            body:
              type: array
              items:
                $ref: '#/components/schemas/Transaction'
    AccountStatementListBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
        - properties:
            body:
              type: array
              items:
                $ref: '#/components/schemas/AccountStatement'
    CategoryListBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
        - properties:
            body:
              type: array
              items:
                $ref: '#/components/schemas/Category'
    BalanceHistoryListBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
        - properties:
            body:
              type: array
              items:
                $ref: '#/components/schemas/BalanceHistory'
    TransferListBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
        - properties:
            body:
              type: array
              items:
                $ref: '#/components/schemas/Transfer'
    BankListBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
        - properties:
            body:
              type: array
              items:
                $ref: '#/components/schemas/Bank'
    CreateAccountStatement:
      type: object
      properties:
        id:
          type: integer
        date:
          type: string
          format: date
        reference:
          type: string
        motif:
          type: string
        credit:
          type: string
          format: bigDecimal
        debit:
          type: string
          format: bigDecimal
        balance:
          type: string
          format: bigDecimal
    CrUpdateAccount:
      type: object
      properties:
        id:
          type: integer
        clientName:
          type: string
        clientFirstName:
          type: string
        birthDate:
          type: string
          format: date
        netMonthlySalary:
          type: string
          format: bigDecimal
        authorize_credits:
          type: boolean
        creation_date:
          type: string
          format: date
        update_date:
          type: string
          format: date
    CrUpdateBalanceHistory:
      type: object
      properties:
        id:
          type: integer
        principalAmount:
          type: string
        moneyLoan:
          type: string
          format: bigDecimal
        loanInterest:
          type: string
          format: bigDecimal
    CrUpdateTransfer:
      type: object
      properties:
        id:
          type: integer
        amount:
          type: string
          format: bigDecimal
        transferReason:
          type: string
        effectiveDate:
          type: string
          format: date
        registrationDate:
          type: string
          format: date
        label:
          type: string
        status:
          type: string
    CrUpdateBank:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        creationDate:
          type: string
          format: date
        updateDate:
          type: string
          format: date
  responses:
    AccountList_200:
      description: List of accounts
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccountListBody'
    TransactionList_200:
      description: List of transactions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TransactionListBody'
    AccountStatementList_200:
      description: List of accounts statements
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccountStatementListBody'
    CategoryList_200:
      description: List of categories
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CategoryListBody'
    BalanceHistoryList_200:
      description: List of balance history
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BalanceHistoryListBody'
    TransferList_200:
      description: List of transfer
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TransferListBody'
    BankList_200:
      description: List of bank
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BankListBody'
    200:
      description: successfully
      content:
        application/json:
          schema:
            $ref: '#/components/responses/200'
    400:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestBody'
    403:
      description: FORBIDDEN
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ForbiddenBody'
    500:
      description: ETERNAL SERVER ERROR
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorServerBody'




